version: "3.7"

services:
    foundry:
        image: felddy/foundryvtt:9.249.0
        environment:
            FOUNDRY_USERNAME:
            FOUNDRY_PASSWORD:
            FOUNDRY_ADMIN_KEY:
            CONTAINER_PRESERVE_CONFIG:
            FOUNDRY_UID:
        hostname: ${FOUNDRY_HOSTNAME}
        ports:
            - "${EXPOSED_FOUNDRY_PORT}:30000/tcp"
        restart: always
        volumes:
            - ${FOUNDRY_DATA_VOLUME}:/data
